# Generated by Django 3.1.1 on 2020-10-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_collegeambassdor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collegeambassdor',
            table='Ambassdor',
        ),
    ]
