# Generated by Django 3.1.1 on 2020-10-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20201024_1212'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collegeambassdor',
            table='CollegeAmbassdor',
        ),
    ]
