# Generated by Django 3.1.1 on 2020-10-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_eventmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
