# Generated by Django 3.1.1 on 2020-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_eventmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
