# Generated by Django 3.1.2 on 2020-10-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
