# Generated by Django 3.1.2 on 2020-10-29 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201029_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='hoster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
